# Generated by Django 5.1.7 on 2025-03-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.SmallIntegerField(
                choices=[(1, "urgent"), (2, "high"), (3, "medium"), (4, "low")],
                default=4,
            ),
        ),
    ]
